services:
  fitness_telegram_bot_v2:
    build: .
    container_name: fitness_telegram_bot_v2
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./app/data:/app/data
      - ./app/config:/app/config
      - ./scripts:/app/scripts

